export const featureList = [
  "Admin Dashboard",
  "User Login",
  "Payment System",
  "Booking System",
  "Contact Form",
  "Live Chat",
  "Notifications",
  "Analytics Dashboard",
  "File Upload",
  "Search Function",
  "Multi Language",
  "Dark Mode",
  "Mobile Responsive",
  "SEO Optimization",
  "Blog System",
  "E-Commerce Store",
  "Inventory Management",
  "Order Tracking",
  "AI Assistant",
  "Custom Design",
  "Other",
];