import type { LucideIcon } from "lucide-react";

import {
  School,
  GraduationCap,
  Stethoscope,
  Hospital,
  Building2,
  Rocket,
  Hotel,
  UtensilsCrossed,
  Briefcase,
  Megaphone,
  HeartHandshake,
  ShoppingBag,
  Landmark,
  Wallet,
  ShieldCheck,
  Dumbbell,
  Pill,
  Plane,
  PlaneTakeoff,
  Truck,
  Warehouse,
  Hammer,
  Factory,
  Cpu,
  Code2,
  Globe,
  User,
  Newspaper,
  Clapperboard,
  CalendarDays,
  Ticket,
  Pizza,
  Car,
  BookOpen,
  Brain,
  Users,
  FolderKanban,
  Boxes,
  Calculator,
  CandlestickChart,
  Bitcoin,
  TrendingUp,
  MessageCircle,
  Gamepad2,
  Gavel,
  CreditCard,
  Crown,
  Church,
  Building,
  RadioTower,
  Bot,
  FlaskConical,
  Library,
  Coffee,
  Scissors,
  Sparkles,
  Gem,
  Monitor,
  Sofa,
  PawPrint,
} from "lucide-react";

interface Props {
  name: string;
}

const iconMap: Record<string, LucideIcon> = {
  Schools: School,
  Universities: GraduationCap,
  Clinics: Stethoscope,
  Hospitals: Hospital,
  Enterprises: Building2,
  Startups: Rocket,
  Hotels: Hotel,
  Restaurants: UtensilsCrossed,
  Brokers: Briefcase,
  Agencies: Megaphone,
  NGOs: HeartHandshake,
  Ecommerce: ShoppingBag,

  Banks: Landmark,
  FinTech: Wallet,
  "Insurance Companies": ShieldCheck,
  "Real Estate": Building,
  "Law Firms": Gavel,
  Gyms: Dumbbell,
  "Fitness Centers": Dumbbell,
  Pharmacies: Pill,
  "Travel Agencies": Plane,
  "Tourism Companies": PlaneTakeoff,
  Airlines: PlaneTakeoff,
  "Logistics Companies": Truck,
  Warehouses: Warehouse,
  "Construction Companies": Hammer,
  Manufacturing: Factory,
  "Cybersecurity Firms": ShieldCheck,
  "IT Companies": Cpu,
  "Software Companies": Code2,
  "Marketing Agencies": Megaphone,
  "Digital Agencies": Globe,
  Freelancers: User,
  "Portfolio Websites": User,
  "Blog Platforms": BookOpen,
  "News Portals": Newspaper,
  "Media Companies": Clapperboard,
  "Streaming Platforms": Clapperboard,
  "Event Management": CalendarDays,
  "Ticket Booking": Ticket,
  "Food Delivery": Pizza,
  "Ride Sharing": Car,
  "Car Rental": Car,
  "Online Learning": GraduationCap,
  "EdTech Platforms": Brain,
  "Job Portals": Briefcase,
  "Recruitment Agencies": Users,
  "HR Management": Users,
  "CRM Systems": FolderKanban,
  "ERP Systems": Boxes,
  "Inventory Systems": Boxes,
  "POS Systems": CreditCard,
  "Accounting Firms": Calculator,
  "Trading Platforms": CandlestickChart,
  "Crypto Platforms": Bitcoin,
  "Investment Firms": TrendingUp,
  "Social Networks": MessageCircle,
  "Community Platforms": Users,
  "Dating Apps": HeartHandshake,
  "Gaming Platforms": Gamepad2,
  "Auction Platforms": Gavel,
  "Marketplace Platforms": ShoppingBag,
  "Subscription Services": CreditCard,
  "Membership Platforms": Crown,
  "Religious Organizations": Church,
  "Government Services": Building,
  "Smart City Projects": RadioTower,
  "IoT Platforms": Cpu,
  "AI Platforms": Bot,
  "Research Centers": FlaskConical,
  Libraries: Library,
  "Coworking Spaces": Coffee,
  "Beauty Salons": Scissors,
  "Spa Centers": Sparkles,
  "Fashion Brands": Sparkles,
  "Jewelry Stores": Gem,
  "Electronics Stores": Monitor,
  "Furniture Stores": Sofa,
  "Pet Care Services": PawPrint,
  "Veterinary Clinics": PawPrint,
};

export default function IndustryBadge({ name }: Props) {
  const Icon = iconMap[name] || Sparkles;

  return (
    <div className="group flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 transition-all duration-300 hover:border-cyan-500/20 hover:bg-white/[0.06]">

      <Icon className="h-4 w-4 text-cyan-400 transition-transform duration-300 group-hover:scale-110" />

      <span className="text-xs font-medium text-zinc-300">
        {name}
      </span>
    </div>
  );
}